try
new test { f1() }
catch done
Class test
	osub = new test2
	x = 10
	func f1
		osub.f2(self)
class test2
	func f2 myobj
		see myobj.x
		